spring.application.name=omnibit

spring.profiles.active=local

server.port=${PORT_OMNIBIT}

base.url=${URL_LOCAL}

spring.datasource.url=${URL_DATABASE}
spring.datasource.username=${DB_USER_NAME}
spring.datasource.password=${DB_PASSWORD}

# Permite que o Hibernate crie as tabelas novas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logs para ver o que está acontecendo
logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.hibernate.orm.jdbc.bind=TRACE
